#!/usr/bin/env bash
set -euo pipefail
repo=$(cd "$(dirname "$0")/.." && pwd -P)
engine="$repo/engine/reference-engine.sh"
n=0
ok(){ n=$((n+1)); echo "ok $n - $1"; }
bad(){ echo "not ok - $1" >&2; exit 1; }
fixture(){
  d=$(mktemp -d "${TMPDIR:-/tmp}/loop-fixture.XXXXXX")
  cp -R "$repo/tests/fixtures/$1/." "$d/"
  cp "$repo/examples/adapters/$2.json" "$d/project.adapter.json"
  chmod +x "$d"/tests/*.sh
  (cd "$d" && git init -q && git add -A && git -c user.name=Fixture -c user.email=fixture@example.invalid commit -qm initial)
  echo "$d"
}
fails(){ name=$1; shift; if "$@" >/dev/null 2>&1; then bad "$name unexpectedly passed"; fi; ok "$name"; }

for pair in 'python-cli python-cli' 'docs-only docs-only'; do
  set -- $pair; d=$(fixture "$1" "$2"); "$engine" snapshot --root "$d" --output "$d.base"
  summary=$($engine verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.evidence")
  jq -e '.status=="PASSED"' "$summary" >/dev/null || bad "$1 did not pass"
  run=$(jq -r .run_id "$summary"); first=$(jq -r '.evidence_ids[0]' "$summary"); jq -e '.details|(.argv|length>0) and (.cwd|length>0) and (.stdout_sha256|test("^[0-9a-f]{64}$")) and (.adapter_sha256|test("^[0-9a-f]{64}$")) and (.node_sha256|test("^[0-9a-f]{64}$")) and (.environment_names|index("PATH")!=null)' "$d.evidence/$run/$first.json" >/dev/null || bad 'provenance missing'
  ok "same engine verifies $1"
done

d=$(fixture python-cli python-cli); "$engine" snapshot --root "$d" --output "$d.base"; "$engine" verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE >/dev/null; "$engine" verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE >/dev/null
ok 'repeated default runs ignore only supervisor-generated evidence deltas'

d=$(fixture python-cli python-cli); "$engine" snapshot --root "$d" --output "$d.base"; jq '.unknown=true' "$d/project.adapter.json" > "$d.bad"
fails 'unknown adapter field fails closed' "$engine" verify --root "$d" --adapter "$d.bad" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture docs-only docs-only); "$engine" snapshot --root "$d" --output "$d.base"; jq '.commands[0].evidence_types=["command","documentation"]' "$d/project.adapter.json" > "$d.bad"
fails 'required evidence needs explicit command mapping' "$engine" verify --root "$d" --adapter "$d.bad" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture python-cli python-cli); "$engine" snapshot --root "$d" --output "$d.base"; jq '.commands[0].argv=["missing-loop-executable"]' "$d/project.adapter.json" > "$d.bad"
fails 'missing executable fails fast' "$engine" verify --root "$d" --adapter "$d.bad" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture docs-only docs-only); "$engine" snapshot --root "$d" --output "$d.base"; mkdir "$d/requirements"; echo changed > "$d/requirements/frozen.md"
fails 'frozen delta fails closed' "$engine" verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture docs-only docs-only); "$engine" snapshot --root "$d" --output "$d.base"; echo changed >> "$d/project.adapter.json"
fails 'protected delta fails closed' "$engine" verify --root "$d" --adapter "$repo/examples/adapters/docs-only.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture docs-only docs-only); "$engine" snapshot --root "$d" --output "$d.base"; echo surprise > "$d/outside.txt"
fails 'non-allowed delta fails closed' "$engine" verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture docs-only docs-only); mkdir -p "$d/.loop/evidence"; echo original > "$d/.loop/evidence/prior.json"; printf '#!/usr/bin/env sh\necho tampered >> .loop/evidence/prior.json\n' > "$d/tests/tamper-evidence.sh"; chmod +x "$d/tests/tamper-evidence.sh"; (cd "$d"&&git add .loop/evidence/prior.json tests/tamper-evidence.sh&&git -c user.name=x -c user.email=x@invalid commit -qm prior); "$engine" snapshot --root "$d" --output "$d.base"; jq '.commands=[{"id":"tamper","phase":"VALIDATE","cwd":".","argv":["tests/tamper-evidence.sh"],"timeout_seconds":5,"evidence_types":["command"]}]|.validation.required_evidence=["command"]' "$d/project.adapter.json" > "$d.tamper"; jq '.verifier_ids=["tamper"]|.run_id="run-prior-evidence"|.gate_id="prior-evidence"' "$d/node.json" > "$d.tampernode"
fails 'prior evidence tamper fails closed' "$engine" verify --root "$d" --adapter "$d.tamper" --node "$d.tampernode" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture docs-only docs-only); "$engine" snapshot --root "$d" --output "$d.base"; printf '#!/usr/bin/env sh\nsleep 3\n' > "$d/tests/check-docs.sh"; chmod +x "$d/tests/check-docs.sh"; jq '.commands[0].timeout_seconds=1' "$d/project.adapter.json" > "$d.timeout"
fails 'command timeout fails closed' "$engine" verify --root "$d" --adapter "$d.timeout" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture python-cli python-cli); "$engine" snapshot --root "$d" --output "$d.base"; rm "$d/src/greet.py"
fails 'missing declared output artifact fails closed' "$engine" verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture docs-only docs-only); outside=$(mktemp -d); ln -s "$outside" "$d/docs/escape"; "$engine" snapshot --root "$d" --output "$d.base"
fails 'workspace symlink escape fails closed' "$engine" verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"
d=$(fixture docs-only docs-only); printf '#!/usr/bin/env sh\ntest -z "${SECRET_SHOULD_NOT_LEAK-}"\n' > "$d/tests/env-check.sh"; chmod +x "$d/tests/env-check.sh"; (cd "$d"&&git add tests/env-check.sh&&git -c user.name=x -c user.email=x@invalid commit -qm env); "$engine" snapshot --root "$d" --output "$d.base"; jq '.commands=[{"id":"env-check","phase":"VALIDATE","cwd":".","argv":["tests/env-check.sh"],"timeout_seconds":5,"evidence_types":["command"]}]|.validation.required_evidence=["command"]' "$d/project.adapter.json" > "$d.envadapter"; jq '.verifier_ids=["env-check"]|.run_id="run-env"|.gate_id="env"' "$d/node.json" > "$d.envnode"; SECRET_SHOULD_NOT_LEAK=topsecret "$engine" verify --root "$d" --adapter "$d.envadapter" --node "$d.envnode" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e" >/dev/null; ok 'environment allowlist blocks undeclared variable'
d=$(fixture docs-only docs-only); printf '#!/usr/bin/env sh\n(sleep 2; echo escaped > descendant.txt) &\nsleep 5\n' > "$d/tests/check-docs.sh"; chmod +x "$d/tests/check-docs.sh"; "$engine" snapshot --root "$d" --output "$d.base"; jq '.commands[0].timeout_seconds=1' "$d/project.adapter.json" > "$d.timeout"; fails 'descendant command times out' "$engine" verify --root "$d" --adapter "$d.timeout" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"; sleep 2; [ ! -e "$d/descendant.txt" ]||bad 'timeout descendant mutated later'; ok 'timeout kills descendant process group'

d=$(fixture python-cli python-cli); "$engine" snapshot --root "$d" --output "$d.base"
summary=$($engine verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e")
run=$(jq -r .run_id "$summary"); id=$(jq -r '.evidence_ids[0]' "$summary"); cp "$d.e/$run/$id.json" "$d.e/$id.json"
"$engine" issue-review --run-id "$run" --work-item TEST-1 --evidence-dir "$d.e" --evidence-ref "$id" --output "$d.challenge"
nonce=$(jq -r .nonce "$d.challenge"); rev=$(git -C "$d" rev-parse HEAD)
jq -n --arg run "$run" --arg nonce "$nonce" --arg rev "$rev" --arg id "$id" '{schema_version:1,verdict_id:"verdict-1",run_id:$run,work_item_id:"TEST-1",phase:"REVIEW",gate_id:"REVIEW",nonce:$nonce,result:"PASS",reviewer:"fixture-independent",independent:true,revision:$rev,captured_at:"2026-09-05T00:00:00Z",evidence_refs:[$id],findings:[]}' > "$d.verdict"
"$engine" validate-verdict --challenge "$d.challenge" --verdict "$d.verdict" --evidence-dir "$d.e" >/dev/null
ok 'exact nonce-bound verdict passes'
fails 'consumed challenge cannot be replayed' "$engine" validate-verdict --challenge "$d.challenge" --verdict "$d.verdict" --evidence-dir "$d.e"
jq '.nonce="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"' "$d.verdict" > "$d.wrong"
fails 'wrong review nonce fails closed' "$engine" validate-verdict --challenge "$d.challenge" --verdict "$d.wrong" --evidence-dir "$d.e"
jq '.captured_at="not-a-date"' "$d.verdict" > "$d.bad-date"
fails 'invalid verdict timestamp fails closed' "$engine" validate-verdict --challenge "$d.challenge" --verdict "$d.bad-date" --evidence-dir "$d.e"
"$engine" issue-review --run-id "$run" --work-item TEST-1 --evidence-dir "$d.e" --evidence-ref "$id" --output "$d.challenge2"; nonce2=$(jq -r .nonce "$d.challenge2"); jq --arg n "$nonce2" '.nonce=$n|.verdict_id="verdict-2"' "$d.verdict" > "$d.verdict2"; jq '.producer="tampered"' "$d.e/$id.json" > "$d.t"; mv "$d.t" "$d.e/$id.json"
fails 'evidence changed after challenge fails closed' "$engine" validate-verdict --challenge "$d.challenge2" --verdict "$d.verdict2" --evidence-dir "$d.e"

d=$(fixture python-cli python-cli); "$engine" snapshot --root "$d" --output "$d.base"; summary=$($engine verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"); run=$(jq -r .run_id "$summary"); typed=$(jq -r '.evidence_ids[]|select(endswith("-behavior"))' "$summary"); cp "$d.e/$run/$typed.json" "$d.e/$typed.json"; echo tampered >> "$d.e/$run/logs/test.stdout"
fails 'typed evidence is bound to immutable command logs' "$engine" issue-review --run-id "$run" --work-item TEST-1 --evidence-dir "$d.e" --evidence-ref "$typed" --output "$d.challenge"

d=$(fixture python-cli python-cli); "$engine" snapshot --root "$d" --output "$d.base"; summary=$($engine verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"); run=$(jq -r .run_id "$summary"); refs=(); while IFS= read -r id; do cp "$d.e/$run/$id.json" "$d.e/$id.json"; refs+=(--evidence-ref "$id"); done < <(jq -r '.evidence_ids[]' "$summary"); now_epoch=$(date +%s); jq -n --argjson start "$now_epoch" '{schema_version:1,work_item_id:"TEST-1",phase:"VALIDATE",run_status:"RUNNING",step:"validate",round:0,max_rounds:4,gate_failures_here:0,max_gate_failures:3,started_epoch:$start,max_wall_seconds:300,autonomy:"supervised",gates:{DEFINE:{status:"PASSED",evidence_ids:[]},DESIGN:{status:"PASSED",evidence_ids:[]},EXECUTE:{status:"PASSED",evidence_ids:[]},REVIEW:{status:"PASSED",evidence_ids:[]},VALIDATE:{status:"PENDING",evidence_ids:[]},HANDOVER:{status:"PENDING",evidence_ids:[]}},last_result:"ready",next_action:"validate",updated_at:"2026-09-05T00:00:00Z"}' > "$d.state"; echo tampered >> "$d.e/$run/logs/test.stdout"
fails 'transition rejects evidence whose bound logs changed' "$engine" transition --root "$d" --state "$d.state" --workflow "$repo/core/workflow.json" --adapter "$d/project.adapter.json" --evidence-dir "$d.e" "${refs[@]}" --to HANDOVER

d=$(fixture python-cli python-cli); "$engine" snapshot --root "$d" --output "$d.base"; summary=$($engine verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"); run=$(jq -r .run_id "$summary"); mapfile=; refs=(); while IFS= read -r id; do cp "$d.e/$run/$id.json" "$d.e/$id.json"; refs+=(--evidence-ref "$id"); done < <(jq -r '.evidence_ids[]' "$summary"); now_epoch=$(date +%s); jq -n --argjson start "$now_epoch" '{schema_version:1,work_item_id:"TEST-1",phase:"VALIDATE",run_status:"RUNNING",step:"validate",round:0,max_rounds:4,gate_failures_here:0,max_gate_failures:3,started_epoch:$start,max_wall_seconds:300,autonomy:"supervised",gates:{DEFINE:{status:"PASSED",evidence_ids:[]},DESIGN:{status:"PASSED",evidence_ids:[]},EXECUTE:{status:"PASSED",evidence_ids:[]},REVIEW:{status:"PASSED",evidence_ids:[]},VALIDATE:{status:"PENDING",evidence_ids:[]},HANDOVER:{status:"PENDING",evidence_ids:[]}},last_result:"ready",next_action:"validate",updated_at:"2026-09-05T00:00:00Z"}' > "$d.state"; cp "$d.state" "$d.illegal"; fails 'illegal transition fails closed' "$engine" transition --root "$d" --state "$d.illegal" --workflow "$repo/core/workflow.json" --adapter "$d/project.adapter.json" --evidence-dir "$d.e" "${refs[@]}" --to DESIGN; jq '.round=.max_rounds' "$d.state" > "$d.capped"; fails 'round cap fails closed' "$engine" transition --root "$d" --state "$d.capped" --workflow "$repo/core/workflow.json" --adapter "$d/project.adapter.json" --evidence-dir "$d.e" "${refs[@]}" --to HANDOVER; jq '.started_epoch=1|.max_wall_seconds=1' "$d.state" > "$d.expired"; fails 'wall cap fails closed' "$engine" transition --root "$d" --state "$d.expired" --workflow "$repo/core/workflow.json" --adapter "$d/project.adapter.json" --evidence-dir "$d.e" "${refs[@]}" --to HANDOVER; "$engine" transition --root "$d" --state "$d.state" --workflow "$repo/core/workflow.json" --adapter "$d/project.adapter.json" --evidence-dir "$d.e" "${refs[@]}" --to HANDOVER; jq -e '.phase=="HANDOVER" and .run_status=="WAITING_FOR_HUMAN" and .round==1 and .gates.VALIDATE.status=="PASSED"' "$d.state" >/dev/null||bad transition; ok 'atomic legal state transition'
d=$(fixture python-cli python-cli); rev=$(git -C "$d" rev-parse HEAD); mkdir -p "$d.e"; jq -n --arg rev "$rev" '{schema_version:1,evidence_id:"define-contract",work_item_id:"TEST-1",phase:"DEFINE",evidence_type:"contract",result:"PASSED",producer:"fixture-supervisor",revision:$rev,environment:"fixture",captured_at:"2026-09-05T00:00:00Z",artifacts:[],details:{observation:"Definition contract approved."}}' > "$d.e/define-contract.json"; now_epoch=$(date +%s); jq -n --argjson start "$now_epoch" '{schema_version:1,work_item_id:"TEST-1",phase:"DEFINE",run_status:"RUNNING",step:"define",round:0,max_rounds:4,gate_failures_here:0,max_gate_failures:3,started_epoch:$start,max_wall_seconds:300,autonomy:"supervised",gates:{DEFINE:{status:"PENDING",evidence_ids:[]},DESIGN:{status:"PENDING",evidence_ids:[]},EXECUTE:{status:"PENDING",evidence_ids:[]},REVIEW:{status:"PENDING",evidence_ids:[]},VALIDATE:{status:"PENDING",evidence_ids:[]},HANDOVER:{status:"PENDING",evidence_ids:[]}},last_result:"ready",next_action:"define",updated_at:"2026-09-05T00:00:00Z"}' > "$d.state"; "$engine" transition --root "$d" --state "$d.state" --workflow "$repo/core/workflow.json" --adapter "$d/project.adapter.json" --evidence-dir "$d.e" --evidence-ref define-contract --to DESIGN; jq -e '.phase=="DESIGN" and .gates.DEFINE.status=="PASSED"' "$d.state" >/dev/null||bad define-transition; ok 'DEFINE uses phase evidence, not VALIDATE evidence policy'; jq '.green_transitions[0].to="HANDOVER"' "$repo/core/workflow.json" > "$d.workflow-bad"; fails 'tampered workflow transition fails closed' "$engine" transition --root "$d" --state "$d.state" --workflow "$d.workflow-bad" --adapter "$d/project.adapter.json" --evidence-dir "$d.e" --evidence-ref define-contract --to EXECUTE
d=$(fixture python-cli python-cli); mkdir -p "$d/.loop/engine.lock"; echo 1 > "$d/.loop/engine.lock/pid"; "$engine" snapshot --root "$d" --output "$d.base"; fails 'workspace lock refuses concurrent verifier' "$engine" verify --root "$d" --adapter "$d/project.adapter.json" --node "$d/node.json" --baseline "$d.base" --phase VALIDATE --evidence-dir "$d.e"; rm -rf "$d/.loop/engine.lock"
outside=$(mktemp -d "${TMPDIR:-/tmp}/loop-init-outside.XXXXXX"); target=$(mktemp -d "${TMPDIR:-/tmp}/loop-init-target.XXXXXX"); ln -s "$outside" "$target/.loop"; fails 'initializer refuses symlinked control directory' "$repo/bootstrap/init.sh" "$target"
echo "1..$n"
